import logging

import transaction
from tg import config

from ldb.config.environment import load_environment

log = logging.getLogger(__name__)

def setup_app(command, conf, vars):
  """Place any commands to setup the Database here"""
  load_environment(conf.global_conf, conf.local_conf)
  # Load the models
  from ldb import model
  print "Creating tables"
  model.metadata.create_all(bind=config['pylons.app_globals'].sa_engine)

  # Create the initial data
  print "Creating initial data"

#
# MANUFACTURERS
#
# (id, name, address, phone, web, about, region_id)
  TallgrassBrewingCo = model.Manufacturer(1,"Tallgrass Brewing Co.", "8845 Quail Lane Manhattan, KS 66502", "(785) 537-1131", "http://www.tallgrassbeer.com/", "Tallgrass Brewing Co. is a microbrewery based out of Manhattan, Kansas.", 1) #region 1 is kansas

  BoulevardBrewingCo = model.Manufacturer(2, "Boulevard Brewing Co.", "2501 Southwest Boulevard Kansas City, MO 64108",	"(816) 474-7095", "http://www.boulevard.com/", "Boulevard Brewing Co. is a microbrewery based out of Kansas City, Missouri.", 2) #region 2 is missouri

  KrackenRumCo = model.Manufacturer(3, "Kracken Rum Co.",	"333 Washington St. Jersey City, NJ 07302", "1-800-837-8452", "http://www.krakenrum.com/site.html","Kracken Rum Co. produces rum from a verity of different spices from Trinidad and Tobago.", 3)#region 3 is NJ

  JohnJamesonandSonsLimited = model.Manufacturer(4, "John Jameson & Sons Limited",	"777 Westchester Ave. West Harrison , NY 10604", "(914) 539-4500", "http://www.jamesonwhiskey.com/","John Jameson & Sons Limited produces Irish Whiskey that is triple distilled to create a more smother taste.", 4) #region 4 is NY

  AustinNicholsDistillingCo = model.Manufacturer(5, "Austin, Nichols Distilling Co.","1525 Tyrone Road Lawrenceburg, KY 40342", "(502) 839-2182", "http://www.wildturkey.com/","Austin, Nichols Distilling Co. produces bourbon under the name Wild Turkey and is based out of Kentucky.", 5) #region 5 is KY

  SamuelAdamsBrewery = model.Manufacturer(6, "Samuel Adams Brewery", "Samuel Adams Brewery, 30 Germania St, Boston, Suffolk, MA 02130-2315", "(617) 368-5080", "www.samueladams.com", "Samuel Adams is an American brand of beer brewed by the Boston Beer Company", 50)

  MccormickDistillingCo = model.Manufacturer(8,"McCormick Distilling Co.", "1 Mc Cormick Ln, Weston, MO 66502", "http://www.mccormickdistilling.com/","(816) 640-2276", "McCormick Distilling, located in historic Weston, Missouri, is the oldest continuously operating distillery in the U.S.", 2)

  HobNobWineCo = model.Manufacturer(9,"HobNob Wine Company", "709 Westchester Ave., Suite 300, White Plains, NY 10604", "http://www.hobnobwines.com/","(914) 251-9463", "HobNob Wine Company offers fine French wines at California prices.", 4)

  WJDeutschSonsLtd = model.Manufacturer(10,"W.J. Deutsch & Sons Ltd.", "709 Westchester Ave., Suite 300, White Plains, NY 10604", "http://www.wjdeutsch.com/","(914) 251-9463", "W.J.Deutsch & Sons builds brands that offer approachable wine experiences which contribute to a premium lifestyle for the mainstream and wine enthusiast consumer.", 4)

  TheWineGroupInc = model.Manufacturer(11,"The Wine Group, Inc.", "315 Montgomery St., San Francisco, CA 94104", "http://www.thewinegroup.org/","(415) 986-8700", "The Wine Group, known for its Franzia wine in a box, the company was founded in 1981.", 6)

  BacardiUsaInc = model.Manufacturer(12,"Bacardi USA, Inc.", "2701 Le Jeune Rd., Coral Gables, FL 33134", "http://www.Barcardi.com/","(305) 573-8511", "Bacardi is a family-controlled spirits company, best known as a producer of rums.", 8)

  SchmittSohneInc = model.Manufacturer(13,"Schmitt Sohne, Inc.", "1111 Benfield Blvd., Suite 112, Millersville, MD 21108", "http://www.schmitt-soehne.com/","(410) 729-4083", "Schmitt Sohne is the leading importer of German Rieslings.", 9)

  ChateauMontelena = model.Manufacturer(14,"Chateau Montelena Winery", "1429 Tubbs Lane, Calistoga, CA 94515", "http://www.montelena.com/","(707) 942-5105", "Chateau Montelena is a Napa Valley winery, most famous for winning the white wine section of the historic Judgement of Paris wine competition.", 6)

  TequilaCuervo = model.Manufacturer(15,"Tequila Cuervo", "230 Park Avenue #812, New York, NY 10169-1009", "http://www.cuervo.com/","(866) 325-4990", "Tequila Cuervo produces tequila, which includes the Jose Cuervo brand.", 4)
  
  HeavenHillDistilleries = model.Manufacturer(16,"Heaven Hill Distilleries, Inc.", "1064 Loretto Road Bardstown, KY 40004", "http://www.heaven-hill.com/","(502) 348-3921", "Heaven Hill Distilleries is the United States' largest independent, family-owned producer and marketer of distilled spirits products.", 5)
  
  KentuckyBourbonDistillersLtd = model.Manufacturer(17,"Kentucky Bourbon Distillers, Ltd", "1869 Loretto Road Bardstown, KY 40004", "http://www.kentuckybourbonwhiskey.com/","(502) 348-0081", "Thompson Willett founded the Willett Distilling Company in 1935.", 5)

  StoneBrewingCo = model.Manufacturer(41, "Stone Brewing Co", "1999 Citracado Parkway Escondido, CA 92029", "(760) 471-4999", "www.stonebrew.com", "Stone Brewing Co. is a craft brewery headquartered in Escondido, California. Founded in 1996 in San Marcos, California,[1] it is the largest brewery in Southern California.", 6)

  NewBelgium = model.Manufacturer(42, "New Belgium Brewing Company", "500 Linden Street Fort Collins, CO, USA", "970-221-0524", "www.newbelgium.com", "Creates New Belgium Beers", 49)

  Rouge = model.Manufacturer(43, "Rouge Brewery", "748 SW Bay Blvd. Newport, OR 97365", "(541) 265-3188", "www.Rogue.com", "Makes Rouge Beer", 48)

  Kuhnhenn = model.Manufacturer(44, "Kuhnhenn Brewing Company", "5919 Chicago Rd, Warren, Michigan, 48092-1606", "(586) 979-836", "www.kbrewery.com", "Makes Brews", 47)

  
  model.DBSession.add(Kuhnhenn)
  model.DBSession.add(Rouge)
  model.DBSession.add(NewBelgium)
  model.DBSession.add(StoneBrewingCo)
  model.DBSession.add(TallgrassBrewingCo)
  model.DBSession.add(BoulevardBrewingCo)
  model.DBSession.add(KrackenRumCo)
  model.DBSession.add(JohnJamesonandSonsLimited)
  model.DBSession.add(AustinNicholsDistillingCo)
  model.DBSession.add(SamuelAdamsBrewery)
  model.DBSession.add(MccormickDistillingCo)
  model.DBSession.add(HobNobWineCo)
  model.DBSession.add(WJDeutschSonsLtd)
  model.DBSession.add(TheWineGroupInc)
  model.DBSession.add(BacardiUsaInc)
  model.DBSession.add(SchmittSohneInc)
  model.DBSession.add(ChateauMontelena)

  model.DBSession.add(TequilaCuervo)
  model.DBSession.add(HeavenHillDistilleries)
  model.DBSession.add(KentuckyBourbonDistillersLtd)


#
# REGIONS
#
# (id, state, about)
  KS = model.Region(1,"Kansas","It's flat with wheat")
  MO = model.Region(2, "Missouri", "NA")
  NJ = model.Region(3,"New Jersey", "most toxic waste sites in the U.S.")
  NY = model.Region(4, "New York", "something about an apple")
  KY = model.Region(5, "Kentucky", "makers of fine bourbon")
  CA = model.Region(6, "California", "beer, wine, cheese, and movies")
  NC = model.Region(7, "North Carolina", "This is a state located in the southeastern US")

  FL = model.Region(8, "Florida", "Florida is a state is located on the nation's Atlantic and Gulf coasts.")
  MD = model.Region(9, "Maryland", "Maryland is a state located in the Mid Atlantic region of the United States.")
  MA = model.Region(50, "Massachusetts", "Boston and some other stuff")
  CO = model.Region(49, "Colorado", "Pretty mountains and low obesity rate")
  OR = model.Region(48, "Oregon", "Nike and rain")
  MI = model.Region(47, "Michigan", "Big Lakes and dying manufacturing plants")

  model.DBSession.add(MI)
  model.DBSession.add(OR)
  model.DBSession.add(CO) 
  model.DBSession.add(KS)
  model.DBSession.add(MO)
  model.DBSession.add(NJ)
  model.DBSession.add(NY)
  model.DBSession.add(KY)
  model.DBSession.add(CA)
  model.DBSession.add(NC)
  model.DBSession.add(FL)
  model.DBSession.add(MD)
  model.DBSession.add(MA)
#
# FOOD
#
# (id, catbeer id, catwine id, name)
# -1 if null...for now
  #wine
  Pasta1 = model.Food(1, -1, 1, "Pasta With White Sauce")
  Pasta2 = model.Food(2, -1, 2, "Pasta With White Sauce")
  Pasta3 = model.Food(3, -1, 6, "Pasta With White Sauce")
  Pasta4 = model.Food(4, -1, 8, "Pasta With White Sauce")

  PastaRed1 = model.Food(5, -1, 3, "Pasta With Red Sauce")
  PastaRed2 = model.Food(6, -1, 4, "Pasta With Red Sauce")
  PastaRed3 = model.Food(7, -1, 5, "Pasta With Red Sauce")
  PastaRed4 = model.Food(8, -1, 7, "Pasta With Red Sauce")
  PastaRed5 = model.Food(9, -1, 9, "Pasta With Red Sauce")

  RedMeat1 = model.Food(10, -1, 3, "Red Meat")
  RedMeat2 = model.Food(11, -1, 4, "Red Meat")
  RedMeat3 = model.Food(12, -1, 5, "Red Meat")
  RedMeat4 = model.Food(13, -1, 7, "Red Meat")
  RedMeat5 = model.Food(14, -1, 9, "Red Meat")
  
  Poultry1 = model.Food(15, -1, 1, "Poultry")
  Poultry2 = model.Food(16, -1, 2, "Poultry")
  Poultry3 = model.Food(17, -1, 6, "Poultry")
  Poultry4 = model.Food(18, -1, 8, "Poultry")

  model.DBSession.add(Pasta1)
  model.DBSession.add(Pasta2)
  model.DBSession.add(Pasta3)
  model.DBSession.add(Pasta4)

  model.DBSession.add(PastaRed1)
  model.DBSession.add(PastaRed2)
  model.DBSession.add(PastaRed3)
  model.DBSession.add(PastaRed4)
  model.DBSession.add(PastaRed5)

  model.DBSession.add(RedMeat1)
  model.DBSession.add(RedMeat2)
  model.DBSession.add(RedMeat3)
  model.DBSession.add(RedMeat4)
  model.DBSession.add(RedMeat5)
  
  model.DBSession.add(Poultry1)
  model.DBSession.add(Poultry2)
  model.DBSession.add(Poultry3)
  model.DBSession.add(Poultry4)

 #beer

  Poultry5 = model.Food(19, 25, -1, "Poultry")
  Poultry6 = model.Food(20, 26, -1, "Poultry")
  Poultry7 = model.Food(21, 27, -1, "Poultry")
  Poultry8 = model.Food(22, 28, -1, "Poultry")
  Poultry9 = model.Food(52, 29, -1, "Poultry")
  Poultry10 = model.Food(23, 30, -1, "Poultry")
  Poultry11 = model.Food(24, 31, -1, "Poultry")
  Poultry12 = model.Food(25, 32, -1, "Poultry")
  Poultry13 = model.Food(26, 1, -1, "Poultry")

  model.DBSession.add(Poultry5)
  model.DBSession.add(Poultry6)
  model.DBSession.add(Poultry7)
  model.DBSession.add(Poultry8)
  model.DBSession.add(Poultry9)
  model.DBSession.add(Poultry10)
  model.DBSession.add(Poultry11)
  model.DBSession.add(Poultry12)
  model.DBSession.add(Poultry13)

  RedMeat6 = model.Food(27, 2, -1, "Red Meat")
  RedMeat7 = model.Food(28, 3, -1, "Red Meat")
  RedMeat8 = model.Food(29, 4, -1, "Red Meat")
  RedMeat9 = model.Food(30, 5, -1, "Red Meat")
  RedMeat10 = model.Food(31, 6, -1, "Red Meat")
  RedMeat11 = model.Food(32, 7, -1, "Red Meat")
  RedMeat12 = model.Food(33, 8, -1, "Red Meat")
  RedMeat13 = model.Food(34, 9, -1, "Red Meat")
  RedMeat14 = model.Food(35, 10, -1, "Red Meat")
  RedMeat15 = model.Food(36, 11, -1, "Red Meat")
  RedMeat16 = model.Food(37, 12, -1, "Red Meat")
  RedMeat17 = model.Food(38, 13, -1, "Red Meat")
  RedMeat18 = model.Food(39, 14, -1, "Red Meat")
  RedMeat19 = model.Food(40, 15, -1, "Red Meat")
  RedMeat20 = model.Food(41, 16, -1, "Red Meat")
  RedMeat21 = model.Food(42, 17, -1, "Red Meat")
  RedMeat22 = model.Food(43, 18, -1, "Red Meat")
  RedMeat23 = model.Food(44, 19, -1, "Red Meat")
  RedMeat24 = model.Food(45, 20, -1, "Red Meat")
  RedMeat25 = model.Food(46, 21, -1, "Red Meat")
  RedMeat26 = model.Food(47, 22, -1, "Red Meat")
  RedMeat27 = model.Food(48, 23, -1, "Red Meat")
  RedMeat28 = model.Food(49, 24, -1, "Red Meat")
  RedMeat29 = model.Food(50, 33, -1, "Red Meat")
  RedMeat30 = model.Food(51, 34, -1, "Red Meat")
 #next key should be 53

  model.DBSession.add(RedMeat6)
  model.DBSession.add(RedMeat7)
  model.DBSession.add(RedMeat8)
  model.DBSession.add(RedMeat9)
  model.DBSession.add(RedMeat10)
  model.DBSession.add(RedMeat11)
  model.DBSession.add(RedMeat12)
  model.DBSession.add(RedMeat13)
  model.DBSession.add(RedMeat14)
  model.DBSession.add(RedMeat15)
  model.DBSession.add(RedMeat16)
  model.DBSession.add(RedMeat17)
  model.DBSession.add(RedMeat18)
  model.DBSession.add(RedMeat19)
  model.DBSession.add(RedMeat20)
  model.DBSession.add(RedMeat21)
  model.DBSession.add(RedMeat22)
  model.DBSession.add(RedMeat23)
  model.DBSession.add(RedMeat24)
  model.DBSession.add(RedMeat25)
  model.DBSession.add(RedMeat26)
  model.DBSession.add(RedMeat27)
  model.DBSession.add(RedMeat28)
  model.DBSession.add(RedMeat29)
  model.DBSession.add(RedMeat30)


#
# WINE CATEGORIES
#
# (id, category, style, about, color, grapes)
  Riesling = model.Wine(1,"White", "Riesling", "NA", "Yellow", "Reisling")
  Chardonnay = model.Wine(2,"White", "Chardonnay", "NA", "White", "Chardonnay")
  PinotNoir = model.Wine(3,"Red", "Pinot Noir", "NA", "Red", "Pinot Noir")
  Merlot = model.Wine(4, "Red", "Merlot", "NA", "Red", "Merlot")
  CabernetSauvignon = model.Wine(5, "Red", "Cabernet Sauvignon", "NA", "Red", "Cabernet Sauvignon")

  SauvignonBlac = model.Wine(6, "White", "Sauvignon Blanc", "NA", "White", "Sauvignon Blac")
  Zinfandel = model.Wine(7, "Red", "Zinfandel", "NA", "Red", "Zinfandel")
  PinotGrigio = model.Wine(8, "White", "Pinot Grigio", "NA", "White", "Pinot Gris")
  Shiraz = model.Wine(9, "Red", "Shiraz", "NA", "Red", "Shiraz")
  
  model.DBSession.add(SauvignonBlac)
  model.DBSession.add(Zinfandel)
  model.DBSession.add(PinotGrigio)
  model.DBSession.add(Shiraz)
  
  model.DBSession.add(Riesling)
  model.DBSession.add(Chardonnay)
  model.DBSession.add(PinotNoir)
  model.DBSession.add(Merlot)
  model.DBSession.add(CabernetSauvignon)

#
# LIQUOR CATEGORIES
#
# (id, category, style, about, color, ingredients)
  SpicedRum = model.Liquor(1, "Rum", "Spiced", "caribbean historically", "white-dark brown", "sugar cane")
  Rum = model.Liquor(2,"Rum", "plain", "caribbean historicaly", "white-dark brown", "sugar cane")
  Bourbon = model.Liquor(3,"Whiskey", "Bourbon", "Southern U.S.", "amber", "corn")
  Rye = model.Liquor(4, "Whiskey", "Rye", "NA", "amber", "rye")
  Scotch = model.Liquor(5, "Whiskey", "Scotch", "Scotland", "amber", "barley")
  Irish = model.Liquor(6, "Whiskey", "Irish", "Ireland", "amber", "barley")
  Vodka = model.Liquor(7, "Vodka", "Vodka", "Russia", "clear", "potatoes")
  Tequila = model.Liquor(8, "Tequila", "Tequila", "Americas", "Clear or brown", "agave")


  model.DBSession.add(SpicedRum)
  model.DBSession.add(Rum)
  model.DBSession.add(Bourbon)
  model.DBSession.add(Rye)
  model.DBSession.add(Scotch)
  model.DBSession.add(Irish)
  model.DBSession.add(Vodka)
  model.DBSession.add(Tequila)
#
# BEER CATEGORIES
#
# (id, category, style, about, color)
  Wheat = model.Beer(1, "Lager" , "Wheat", "made with wheat, sometimes in addition to barley and sometimes entirely of wheat. Often unfiltered", "semi-opaque gold")
  DoubleESB = model.Beer(2, "Ale", "DoubleESB", "extra strong/special bitter", "predominantly dark beers")
  AmberAle = model.Beer(3, "Ale", "Amber Ale", "NA", "amber")
  PaleAle = model.Beer(4, "Ale", "Pale Ale", "NA", "light amber, gold")
  IPA = model.Beer(5, "Ale", "IPA", "Heavily hopped beer", "NA")
  Stout = model.Beer(6, "Ale", "Stout", "lightly hopped and heavily malted beers with well roasted malt", "Dark brown/black")
  AmericanBrownAle = model.Beer(7,"Ale", "American Brown Ale", "often a mix of european malts to create a uniquely American brew", "brown")

  BarleyWine = model.Beer(8,"Ale", "Barely Wine", "Strong beer (10-18 ABV) that is ususally stored for 18 months to two years", "Dark")
  BlondAle  = model.Beer(9, "Ale", "Blond Ale", "An American invention created from the craft brew movement, this beer is similar to a Kolsch. Often an all malt brew, lightly hopped and similar to some lagers", "Pale straw to deep gold")
  Dubbel  = model.Beer(10, "Ale", "Dubbel", "Rich malty Belgian beer with mild hoppiness and caramel malt", "dark amber")
  Quadrupel  = model.Beer(11, "Ale", "Quadrupel", "Strong Belgian style ale with low bitterness and full bodied malt, often high ABV", "dark brown, garnet")
  Trappist = model.Beer(13, "Ale", "Trappist", "Only seven trappist breweries in the world, refers to the association with monasitc orders", "NA")
  Tripel  = model.Beer(14, "Ale", "Tripel", "Name refers to use of three times as much malt that standard trappist ale. Dense and creamy beer with heavy maltiness and balanced hoppiness. High ABV", "gold")
  Porter = model.Beer(15, "Ale", "Porter", "An English beer popular among the working class, the porter is often lighter than the stout with moderate bitterness", "dark brown to black")
  Kolsch  = model.Beer(34, "Ale", "Kolsch", "Originally from Koln, Germany, this beer is light to medium bodied with with assertive hoppiness", "pale")
  Altbier  = model.Beer(16, "Ale", "Altbier", "A German style brown ale with a longer period of fermentaion than most beers. Medium bodied with a balance between malt and hops", "amber to dark brown")
  EnglishBitter  = model.Beer(17, "Ale", "English Bitter", "The English bitter is composed of pale malts, high hop levels, and low carbonation", "gold to copper")
  Saison  = model.Beer(18, "Ale", "Saison", "Sometimes called country beer, this medium alcohol beer is originally from rural Belgium, often spicy", "orange, brown, some pale")
  ScotchAle  = model.Beer(19, "Ale", "Scotch Ale", "Heavily carmalized wort results in low hop character and hight maltiness, sometimes smokey", "deep copper to brown")
  Weisse  = model.Beer(20, "Ale", "Weisse", "A bottle conditioned beer with sour and tart flavor. Sometimes flavored with fruit", "pale gold, straw")
  Dunkel  = model.Beer(21, "Ale", "Dunkel", "A German wheat beer brewed with darker malts and and containing a low bitterness", "Brown and hazy")
  Hefeweizen  = model.Beer(22, "Ale", "Hefewizen", "A German wheat beer made with high quantities of wheat, typically unfiltered and cloudy", "pale straw")
  Weizenbock  = model.Beer(23, "Ale", "Weizenbock", "A heavier version of the dunkel, often high ABV", "dark brown")
  Witbier  = model.Beer(24, "Ale", "Witbier", "Wit, or white, is often pale golden and tart with high levels of CO2" , "pale golden")
  Doppelbock  = model.Beer(25, "Lager", "Doppelbock", "The doppelbock is a stronger, maltier version of the boch, often called a meal in a glass", "dark amber to black")
  Eisbock  = model.Beer(26, "Lager", "Eisbock", "The Eisbock is created by freezing of a portion of the water from the beer and removing it, this results in a high ABV of 9-15", "black to straw to red")
  Maibock  = model.Beer(27, "Lager", "Maibock", "A light boch, the Maibock has a significant hop flavor and is often a spring beer", "light straw")
  Marzen  = model.Beer(28, "Lager", "Marzen", "Also know as an Octoberfest, the Marzen is traditionally brewed during colder months. The marzen has a medium to high alcohol content and is typically full bodied with rich maltiness", "dark copper")
  Dortmunder  = model.Beer(29, "Lager", "Dortmunder", "A bitter lager with discuity malts", "pale gold")
  Pilsner  = model.Beer(30, "Lager", "Pilsner", "Most produced beer in the world. Examples include Budweiser and Coors", "light gold")
  Schwarzbier  = model.Beer(31, "Lager", "Schwarzbier", "A German black beer, the name does not refer to characteristics", "black")
  Kellerbier  = model.Beer(32, "Lager", "Kellerbier", "An unpasterurized lager dating back to the middle ages with a cloudy look and high hoppiness", "straw to golden")
  Lambic  = model.Beer(33, "Ale", "Lambic", "A beer that is brewed traditionaly with wild yeast and bacteria in tainted barrels, the lambic has tart bitterness similar to a cider", "cloudy straw")

  model.DBSession.add(BarleyWine)
  model.DBSession.add(BlondAle)
  model.DBSession.add(Dubbel)
  model.DBSession.add(Quadrupel)
  model.DBSession.add(Trappist)
  model.DBSession.add(Tripel)
  model.DBSession.add(Porter)
  model.DBSession.add(Kolsch)
  model.DBSession.add(Altbier)
  model.DBSession.add(EnglishBitter)
  model.DBSession.add(Saison)
  model.DBSession.add(ScotchAle)
  model.DBSession.add(Weisse)
  model.DBSession.add(Dunkel)
  model.DBSession.add(Hefeweizen)
  model.DBSession.add(Weizenbock)
  model.DBSession.add(Witbier)
  model.DBSession.add(Doppelbock)
  model.DBSession.add(Eisbock)
  model.DBSession.add(Maibock)
  model.DBSession.add(Marzen)
  model.DBSession.add(Dortmunder)
  model.DBSession.add(Pilsner)
  model.DBSession.add(Schwarzbier)
  model.DBSession.add(Kellerbier)
  model.DBSession.add(Lambic)

  model.DBSession.add(Wheat)
  model.DBSession.add(DoubleESB)
  model.DBSession.add(AmberAle)
  model.DBSession.add(PaleAle)
  model.DBSession.add(IPA)
  model.DBSession.add(Stout)
  model.DBSession.add(AmericanBrownAle)

#
# DRINKS
#
# (id, name, abv, manu_id, catbeer ID, catLiquor ID, catWine ID)
# -1 if null....for now
   
  TallgrassBuffaloSweat = model.Drink(100, "Buffalo Sweat", 5.0, 1,6,-1,-1)
  TallgrassIPA = model.Drink(101, "IPA", 6.3, 1, 5,-1,-1)
  BoulevardBob = model.Drink(102, "Bob's 47 Oktoberfest",5.8, 2, 28, -1, -1)
  BoulevardBoss = model.Drink(103, "Boss Tom's Golden Bock", 6.1, 2, 27, -1, -1)
  BoulevardBully = model.Drink(104, "Bully! Porter", 5.4, 2, 15, -1, -1)
  BoulevardTruth = model.Drink(105, "Dark Truth Stout", 9.7, 2, 6, -1,-1)
  BoulevardIPA = model.Drink(106, "Double-Wide IPA", 8.5, 2, 5, -1, -1)
  BoulevardDry = model.Drink(107, "Dry Stout", 4.9 ,2, 6, -1, -1)
  BoulevardTripel = model.Drink(108, "Long Strange Tripel", 9, 2, 14, -1, -1)
  BoulevardPilsner = model.Drink(109, "Pilsner", 4.8, 2, 30, -1,-1)
  BoulevardWide = model.Drink(110, "Single-Wide IPA", 5.7, 2, 5, -1,-1)
  BoulevardFarmhouse = model.Drink(111, "Tank 7 Farmhouse Ale", 8, 2, 18, -1,-1)
  BoulevardSixth = model.Drink(112, "The Sixth Glass", 10.5, 2, 11, -1, -1)
  BoulevardZon = model.Drink(113, "ZON belgian-style Witbier", 4.4, 2, 24, -1, -1)
  SamBoston = model.Drink(114, "Boston Lager", 4.9, 40, 25, -1, -1)
  SamDunkel = model.Drink(115, "Dunkelweizen", 5.1, 40, 21, -1, -1)
  SamPorter = model.Drink(116, "Holiday Porter", 5.8, 40, 15,-1,-1)
  SamPils = model.Drink(117, "Noble Pils", 4.9, 40, 30, -1,-1)
  SamMarzen = model.Drink(118, "Octoberfest", 5.3, 40, 28, -1,-1)
  SamSummerAle = model.Drink(119, "Summer Ale", 5.3, 40, 1, -1,-1)
  SamWhiteAle = model.Drink(120, "White Ale", 5.3, 40, 24, -1,-1)
  SamKolsch = model.Drink(121, "East West Kolsch", 5.0, 40, 15, -1,-1)
  SamSaison = model.Drink(122, "Rustic Saison", 4.4, 40, 18, -1,-1)
  SamCoastal = model.Drink(123, "Coastal Wheat", 5.4, 40, 22, -1, -1)
  SamPale = model.Drink(124, "Pale Ale" , 5.4, 40, 4, -1,-1)
  SamScotch = model.Drink(125, "Scotch Ale", 5.5, 40, 19, -1,-1)
  SamBock = model.Drink(126, "Double Bock", 9.5, 40, 25, -1,-1)
  StonePale = model.Drink(127, "Pale Ale", 5.4, 41, 4, -1,-1)
  StonePorter = model.Drink(128, "Smoked Porter", 5.9, 41, 15, -1,-1)
  StoneIPA = model.Drink(129, "IPA", 6.9, 41, 5, -1, -1)
  StoneBarleyWine = model.Drink(130, "Old Guardian Barley Wine", 12, 41, 8,-1,-1)
  NewSunshine = model.Drink(131, "Sunshine Wheat Beer", 4.8, 42, 1, -1,-1)
  NewFat = model.Drink(132, "Fat Tire", 5.2,42, 3, -1,-1)
  NewBlue = model.Drink(133, "Blue Paddle", 4.8, 42, 30, -1,-1)
  NewTrippel = model.Drink(134, "Trippel", 7.8, 42, 14, -1,-1)
  NewRanger = model.Drink(135, "Ranger", 6.5, 42, 5, -1,-1)
  NewBelgo = model.Drink(136, "Belgo", 7.0, 42,5, -1,-1)
  NewMother = model.Drink(137, "Mothership Wit", 4.8, 42,24, -1,-1) 
  RougeAmber = model.Drink(138, "American Amber Ale", 5.6, 43, 3, -1,-1)
  RougeBlack = model.Drink(139, "Chatoe Rogue First Growth Dirtoir Black Lager", 6.0, 43, 31, -1,-1)
  RougeSingle = model.Drink(140, "Single Malt Ale", 5.3, 43, 9, -1, -1)
  RougeDead = model.Drink(141, "Dead Guy Ale", 6.5, 43, 27, -1,-1)
  RougeFestive = model.Drink(142, "Festive Ale", 6.2, 43, 18, -1,-1)
  RougeQuad = model.Drink(143, "Issaqah Quad Frog", 13.5, 43, 11, -1, -1)
  RougeMarzen = model.Drink(144, "Maierfest Lager", 5.6, 43, 28, -1,-1)
  RougeBlack = model.Drink(145, "Rouge Black Brutal", 9, 43, 31, -1,-1)
  RougeWine = model.Drink(146, "XS Old Crustacean", 11.5, 43, 8,-1,-1)
  KuhnEis = model.Drink(147, "Eisbock", 13, 44, 26, -1,-1)
    
  TallgrassHalcyon = model.Drink(1,"Halcyon", 5, 1,1,-1,-1)
  TallgrassAle = model.Drink(2,"Tallgrass Ale", 4.4, 1,7,-1,-1)
  TallgrassOasis = model.Drink(3, "Oasis", 7.2, 1, 2, -1,-1)
  BoulevardAmberAle = model.Drink(4, "Amber Ale", 5.1, 2,3,-1,-1)

  BoulevardPaleAle = model.Drink(5,"Pale Ale", 5.4, 2, 4, -1,-1)
  TheKrackenBlackSpicedRum = model.Drink(6, "The Kracken Black Spiced Rum", 47, 3,-1,1,-1)
  JamesonIrishWhiskey = model.Drink(7, "Jameson Irish Whiskey", 40, 5,-1,6,-1)
  WildTurkeyBourbon = model.Drink(8, "Wild Turkey", 50.5, 5, -1,3,-1)
  BacardiSuperior = model.Drink(9, "Bacardi Superior", 40, 12, -1,2,-1)
  McCormickVodka = model.Drink(10, "McCormick Vodka", 40, 8, -1, 7, -1)

  RelaxRiesling = model.Drink(11, "Relax Riesling", 9.5, 13, -1,-1, 1)
  HobnobPinotNoir = model.Drink(12, "Hobnob Pinot Noir", 13, 9, -1,-1,3)
  YellowTailChardonnay = model.Drink(13, "Yellow Tail Chardonnay", 13.5, 10, -1,-1,2)
  FranziaMerlot = model.Drink(14, "Franzia Merlot", 8.8, 11, -1,-1,4)
  MontelenaEstateCabernetSauvignon = model.Drink(15, "Montelena Estate Cabernet Sauvignon", 14.3, 14, -1, -1 , 5)

  model.DBSession.add(TallgrassBuffaloSweat)
  model.DBSession.add(TallgrassIPA)
  model.DBSession.add(BoulevardBob)
  model.DBSession.add(BoulevardBoss)
  model.DBSession.add(BoulevardBully)
  model.DBSession.add(BoulevardTruth)
  model.DBSession.add(BoulevardIPA)
  model.DBSession.add(BoulevardDry)
  model.DBSession.add(BoulevardTripel)
  model.DBSession.add(BoulevardPilsner)
  model.DBSession.add(BoulevardWide)
  model.DBSession.add(BoulevardFarmhouse)
  model.DBSession.add(BoulevardSixth)
  model.DBSession.add(BoulevardZon)
  model.DBSession.add(SamBoston)
  model.DBSession.add(SamDunkel)
  model.DBSession.add(SamPorter)
  model.DBSession.add(SamPils)
  model.DBSession.add(SamMarzen)
  model.DBSession.add(SamSummerAle)
  model.DBSession.add(SamWhiteAle)
  model.DBSession.add(SamKolsch)
  model.DBSession.add(SamSaison)
  model.DBSession.add(SamCoastal)
  model.DBSession.add(SamPale)
  model.DBSession.add(SamScotch)
  model.DBSession.add(SamBock)
  model.DBSession.add(StonePale)
  model.DBSession.add(StonePorter)
  model.DBSession.add(StoneIPA)
  model.DBSession.add(StoneBarleyWine)
  model.DBSession.add(NewSunshine)
  model.DBSession.add(NewFat)
  model.DBSession.add(NewBlue)
  model.DBSession.add(NewTrippel)
  model.DBSession.add(NewRanger)
  model.DBSession.add(NewBelgo)
  model.DBSession.add(NewMother)
  model.DBSession.add(RougeAmber)
  model.DBSession.add(RougeBlack)
  model.DBSession.add(RougeSingle)
  model.DBSession.add(RougeDead)
  model.DBSession.add(RougeFestive)
  model.DBSession.add(RougeQuad)
  model.DBSession.add(RougeMarzen)
  model.DBSession.add(RougeBlack)
  model.DBSession.add(RougeWine)
  model.DBSession.add(KuhnEis)
  
  model.DBSession.add(TallgrassHalcyon)
  model.DBSession.add(TallgrassAle)
  model.DBSession.add(TallgrassOasis)
  model.DBSession.add(BoulevardAmberAle)
  model.DBSession.add(BoulevardPaleAle)
  model.DBSession.add(TheKrackenBlackSpicedRum)
  model.DBSession.add(JamesonIrishWhiskey)
  model.DBSession.add(WildTurkeyBourbon)
  model.DBSession.add(BacardiSuperior)
  model.DBSession.add(McCormickVodka)
  model.DBSession.add(RelaxRiesling)
  model.DBSession.add(HobnobPinotNoir)
  model.DBSession.add(YellowTailChardonnay)
  model.DBSession.add(FranziaMerlot)
  model.DBSession.add(MontelenaEstateCabernetSauvignon)

  #liquor
  EspecialGold = model.Drink(16, "Especial Tequila Gold", 40, 15, -1, 8, -1)
  EspecialSilver = model.Drink(17, "Especial Tequila Silver", 40, 15, -1, 8, -1)
  BlackMedallion = model.Drink(18, "Black Medallion", 40, 15, -1, 8, -1)
  TradicionalSilver = model.Drink(19, "Tradicional Silver Tequila", 40, 15, -1, 8, -1)
  CuervoPlatino = model.Drink(20, "Jose Cuervo Platino", 40, 15, -1, 8, -1)
  ReservaFamilia = model.Drink(21, "Reserva de la Familia", 40, 15, -1, 8, -1)
  EvanWilliams98 = model.Drink(22, "Evan Williams 1998 Vintage Bourbon", 43.3, 16, -1, 3, -1)
  ElijahCraig12yr = model.Drink(23, "Elijah Craig 12yr Bourbon", 47, 16, -1, 3, -1)
  ElijahCraig18yr = model.Drink(24, "Elijah Craig 18yr Bourbon", 45, 16, -1, 3, -1)
  EvanWilliams94 = model.Drink(25, "Evan Williams 1994 Vintage Bourbon", 43.3, 16, -1, 3, -1)
  EvanWilliams95 = model.Drink(26, "Evan Williams 1995 Vintage Bourbon", 43.3, 16, -1, 3, -1)
  EvanWilliams96 = model.Drink(27, "Evan Williams 1996 Vintage Bourbon", 43.3, 16, -1, 3, -1)
  EvanWilliams97 = model.Drink(28, "Evan Williams 1997 Vintage Bourbon", 43.3, 16, -1, 3, -1)
  EvanWilliams98 = model.Drink(29, "Evan Williams 1999 Vintage Bourbon", 43.3, 16, -1, 3, -1)
  Rittenhouse100 = model.Drink(30, "Rittenhouse 100", 50, 16, -1, 4, -1)
  Rittenhouse21 = model.Drink(31, "Rittenhouse 21yr", 50, 16, -1, 4, -1)
  Rittenhouse23 = model.Drink(32, "Rittenhouse 23yr", 50, 16, -1, 4, -1)
  Rittenhouse25 = model.Drink(33, "Rittenhouse 25yr", 50, 16, -1, 4, -1)
  EvanWilliams00 = model.Drink(34, "Evan Williams 2000 Vintage Bourbon", 43, 16, -1, 3, -1)
  EvanWilliams01 = model.Drink(35, "Evan Williams 2001 Vintage Bourbon", 43.3, 16, -1, 3, -1)
  WhalerSpiced = model.Drink(36, "Whaler's Original Spiced Rum", 35, 16, -1, 1, -1)
  WhalerWhite = model.Drink(37, "Whaler's Great White Rum", 40, 16, -1, 2, -1)
  WhalerRare = model.Drink(38, "Whaler's Rare Reserve", 40, 16, -1, 1, -1)
  McllhennyTabascoTequila =  model.Drink(39, "Tabasco Spicy Tequila", 40, 16, -1, 8, -1)
  RebelYellBourbon = model.Drink(40, "Rebel Yell", 40, 16, -1, 3, -1)
  EvanWilliams7r = model.Drink(41, "Evan Williams 7yr Bourbon", 43, 16, -1, 3, -1)
  TwoFingers = model.Drink(42, "Two Fingers", 40, 16, -1, 8, -1)
  PikesvillRye = model.Drink(43, "Pikesville Rye", 40, 16, -1, 4, -1)
  ParkersHeritage = model.Drink(44, "Parker's Heritage Bourbon", 50, 16, -1, 3, -1)
  BurnettsCherry = model.Drink(45, "Burnett's Cherry Flavored Vodka", 35, 16, -1, 7, -1)
  BurnettsLime = model.Drink(46, "Burnett's Lime Flavored Vodka", 35, 16, -1, 7, -1)
  BurnettsPeach = model.Drink(47, "Burnett's Peach Flavored Vodka", 35, 16, -1, 7, -1)
  Burnetts = model.Drink(48, "Burnett's Vodka", 40, 16, -1, 7, -1)
  BurnettsCranberry = model.Drink(49, "Burnett's Cranberry Flavored Vodka", 35, 16, -1, 7, -1)
  BurnettsCitrus = model.Drink(50, "Burnett's Citrus Flavored Vodka", 35, 16, -1, 7, -1)

  BlackMaple18Rye = model.Drink(93, "Black Maple 18yr Rye", 47.5, 17, -1, 4, -1)
  BlackMaple11 = model.Drink(94, "Black Maple Hill 11yr", 47.5, 17, -1, 3, -1)
  BlackMaple14 = model.Drink(95, "Black Maple Hill 14yr", 47.5, 17, -1, 3, -1)
  BlackMaple16 = model.Drink(96, "Black Maple Hill 16yr", 47.5, 17, -1, 3, -1)
  BlackMaple21 = model.Drink(97, "Black Maple Hill 21yr", 47.5, 17, -1, 3, -1)
  BlackMaple23 = model.Drink(98, "Black Maple Hill 23yr", 48, 17, -1, 3, -1)
  BlackMapleSmall = model.Drink(99, "Black Maple Hill Small Batch", 47.5, 17, -1, 3, -1)

  model.DBSession.add(EspecialGold)
  model.DBSession.add(EspecialSilver)
  model.DBSession.add(BlackMedallion)
  model.DBSession.add(TradicionalSilver)
  model.DBSession.add(CuervoPlatino)
  model.DBSession.add(ReservaFamilia)
  model.DBSession.add(EvanWilliams98)
  model.DBSession.add(ElijahCraig12yr)
  model.DBSession.add(ElijahCraig18yr)
  model.DBSession.add(EvanWilliams94)
  model.DBSession.add(EvanWilliams95)
  model.DBSession.add(EvanWilliams96)
  model.DBSession.add(EvanWilliams97)
  model.DBSession.add(EvanWilliams98)
  model.DBSession.add(Rittenhouse100)
  model.DBSession.add(Rittenhouse21)
  model.DBSession.add(Rittenhouse23)
  model.DBSession.add(Rittenhouse25)
  model.DBSession.add(EvanWilliams00)
  model.DBSession.add(EvanWilliams01)
  model.DBSession.add(WhalerSpiced)
  model.DBSession.add(WhalerWhite)
  model.DBSession.add(WhalerRare)
  model.DBSession.add(McllhennyTabascoTequila)
  model.DBSession.add(RebelYellBourbon)
  model.DBSession.add(EvanWilliams7r)
  model.DBSession.add(TwoFingers)
  model.DBSession.add(PikesvillRye)
  model.DBSession.add(ParkersHeritage)
  model.DBSession.add(BurnettsCherry)
  model.DBSession.add(BurnettsLime)
  model.DBSession.add(BurnettsPeach)
  model.DBSession.add(Burnetts)
  model.DBSession.add(BurnettsCranberry)
  model.DBSession.add(BurnettsCitrus)
  
  model.DBSession.add(BlackMaple18Rye)
  model.DBSession.add(BlackMaple11)
  model.DBSession.add(BlackMaple14)
  model.DBSession.add(BlackMaple16)
  model.DBSession.add(BlackMaple21)
  model.DBSession.add(BlackMaple23)
  model.DBSession.add(BlackMapleSmall)

  #wine
  NineWalksSauvignonBlanc = model.Drink(51, "Nine Walks Sauvignon Blanc", 13.4, 10, -1, -1 , 6)
  JoshCellarsChardonnay = model.Drink(52, "Josh Cellars Chardonnay", 12.5, 10, -1, -1 , 2)
  FranziaZinfandel = model.Drink(53, "Franzia Zinfandel", 8, 11, -1, -1 , 7)
  FranziaCabernetSauvignon = model.Drink(54, "Franzia Cabernet Sauvignon", 8, 11, -1, -1 , 5)
  BlueRieslingAuslese = model.Drink(55, "Blue Riesling Auslese", 8.5, 13, -1, -1 , 1)
  BereichBingenAuslese = model.Drink(56, "Bereich Bingen Auslese", 10.5, 13, -1, -1 , 1)
  YellowTailCabernetSauvignon = model.Drink(57, "Yellow Tail Cabernet Sauvignon", 13.5, 10, -1,-1, 5)
  YellowTailMerlot = model.Drink(58, "Yellow Tail Merlot", 11, 10, -1,-1, 4)
  YellowTailPinotGrigio = model.Drink(59, "Yellow Tail Pinot-Grigio", 11.5, 10, -1,-1, 8)
  YellowTailPinotNoir = model.Drink(60, "Yellow Tail Pinot Noir", 13.5, 10, -1,-1, 3)
  YellowTailRiesling = model.Drink(61, "Yellow Tail Riesling", 12.5, 10, -1,-1, 1)
  YellowTailShiraz = model.Drink(62, "Yellow Tail Shiraz", 13.5, 10, -1,-1, 9)
  BaroneFiniMerlot = model.Drink(63, "Barone Fini Merlot", 14, 10, -1,-1, 4)
  BaroneFiniPinotGrigio = model.Drink(64, "Barone Fini Pinot Grigio", 12.5, 10, -1,-1, 4)
  GirardSauvignonBlac = model.Drink(65, "Girard Sauvignon Blac", 13.9, 10, -1,-1, 6)
  GirardCabernetSauvignon = model.Drink(66, "Girard Cabernet Sauvignon", 14.5, 10, -1,-1, 5)
  GirardChardonnay = model.Drink(67, "Girard Chardonnay", 13.9, 10, -1,-1, 2)
  GirardOldVineZinfandel = model.Drink(68, "Girard Old Vine Zinfandel", 14.7, 10, -1,-1, 7)
  KundeFamilyEstateCabernetSauvignon = model.Drink(69, "Kunde Family Estate Cabernet Sauvignon", 13.8, 10, -1,-1, 5)
  KundeFamilyEstateChardonnay = model.Drink(70, "Kunde Family Estate Chardonnay", 13.8, 10, -1,-1, 2)
  KundeFamilyEstateMerlot = model.Drink(71, "Kunde Family Estate Merlot", 13.8, 10, -1,-1, 4)
  PatchBlockMerlot = model.Drink(72, "Patch Block Merlot", 14.5, 10, -1,-1, 4)
  PatchBlockCabernetSauvignon = model.Drink(73, "Patch Block Cabernet Sauvignon", 14.5, 10, -1,-1, 5)
  PatchBlockChardonnay = model.Drink(74, "Patch Block Chardonnay", 12.5, 10, -1,-1, 2)
  PatchBlockPinotNoir = model.Drink(75, "Patch Block Pinot Noir", 14.9, 10, -1,-1, 3)
  PatchBlockSauvignonBlac = model.Drink(76, "Patch Block Sauvignon Blac", 12.5, 10, -1,-1, 6)
  FranziaChardonnay = model.Drink(77, "Franzia Chardonnay", 12, 11, -1, -1 , 2)
  FranziaShiraz = model.Drink(78, "Franzia Shiraz", 8, 11, -1, -1 , 9)
  NapaValleyChardonnay = model.Drink(79, "Napa Valley Chardonnay", 13.6, 14, -1,-1, 2)
  NapaValleyCabernetSauvignon = model.Drink(80, "Napa Valley Cabernet Sauvignon", 14.2, 14, -1,-1, 5)
  MontelenaEstateZinfandel = model.Drink(81, "Montelena Estate Zinfandel", 14.7, 14, -1,-1, 7)
  PotterValleyRiesling = model.Drink(82, "Potter Valley Riesling", 14.4, 14, -1,-1, 1)
  BlueRieslingKabinett = model.Drink(83, "Blue Riesling Kabinett", 7.5, 13, -1, -1 , 1)
  BlueRiesling = model.Drink(84, "Blue Riesling", 9, 13, -1, -1 , 1)
  PiesporterMichelsberg = model.Drink(85, "Piesporter Michelsberg", 9, 13, -1, -1 , 1)
  PiesporterMichelsbergKabinett = model.Drink(86, "Piesporter Michelsberg Kabinett", 8, 13, -1, -1 , 1)
  PiesporterMichelsbergAuslese = model.Drink(87, "Piesporter Michelsberg Auslese", 8, 13, -1, -1 , 1)
  BereichBernkastel = model.Drink(88, "Bereich Bernkastel", 8.5, 13, -1, -1 , 1)
  ZellerSchwarzeKatz = model.Drink(89, "Zeller Schwarze Katz", 9, 13, -1, -1 , 1)
  MoselGoldRiesling = model.Drink(90, "MoselGoldRiesling", 9, 13, -1, -1 , 1)
  SchmittSoehneRiesling = model.Drink(91, "Schmitt Soehne Riesling", 9, 13, -1, -1 , 1)
  SchmittSoehnePinotGrigio = model.Drink(92, "Schmitt Soehne Pinot Grigio", 9, 13, -1, -1 , 3)

# wine
  model.DBSession.add(NineWalksSauvignonBlanc)
  model.DBSession.add(JoshCellarsChardonnay)
  model.DBSession.add(FranziaZinfandel)
  model.DBSession.add(FranziaCabernetSauvignon)
  model.DBSession.add(BlueRieslingAuslese)
  model.DBSession.add(BereichBingenAuslese)
  model.DBSession.add(YellowTailCabernetSauvignon)
  model.DBSession.add(YellowTailMerlot)
  model.DBSession.add(YellowTailPinotGrigio)
  model.DBSession.add(YellowTailPinotNoir)
  model.DBSession.add(YellowTailRiesling)
  model.DBSession.add(YellowTailShiraz)
  model.DBSession.add(BaroneFiniMerlot)
  model.DBSession.add(BaroneFiniPinotGrigio)
  model.DBSession.add(GirardSauvignonBlac)
  model.DBSession.add(GirardCabernetSauvignon)
  model.DBSession.add(GirardChardonnay)
  model.DBSession.add(GirardOldVineZinfandel)
  model.DBSession.add(KundeFamilyEstateCabernetSauvignon)
  model.DBSession.add(KundeFamilyEstateChardonnay)
  model.DBSession.add(KundeFamilyEstateMerlot)
  model.DBSession.add(PatchBlockMerlot)
  model.DBSession.add(PatchBlockCabernetSauvignon)
  model.DBSession.add(PatchBlockChardonnay)
  model.DBSession.add(PatchBlockPinotNoir)
  model.DBSession.add(PatchBlockSauvignonBlac)
  model.DBSession.add(PotterValleyRiesling)
  model.DBSession.add(FranziaChardonnay)
  model.DBSession.add(FranziaShiraz)
  model.DBSession.add(NapaValleyChardonnay)
  model.DBSession.add(NapaValleyCabernetSauvignon)
  model.DBSession.add(MontelenaEstateZinfandel)
  model.DBSession.add(PotterValleyRiesling)
  model.DBSession.add(BlueRieslingKabinett)
  model.DBSession.add(BlueRiesling)
  model.DBSession.add(PiesporterMichelsberg)
  model.DBSession.add(PiesporterMichelsbergKabinett)
  model.DBSession.add(PiesporterMichelsbergAuslese)
  model.DBSession.add(BereichBernkastel)
  model.DBSession.add(ZellerSchwarzeKatz)
  model.DBSession.add(MoselGoldRiesling)
  model.DBSession.add(SchmittSoehneRiesling)
  model.DBSession.add(SchmittSoehnePinotGrigio)

  transaction.commit()
  print "successfully setup"

